### ISSUE TITLE
Support for disabling TLS in the tool (to be used on macOS)

### ISSUE THREAD

**Issue by ChristianWeyer** [bjorkstromm/dotnet-grpc-cli#3]
Hi @bjorkstromm 

when using the tool with a gRPC service on .NET 5 on macOS, we get this error when trying to list the services:

```
dotnet grpc-cli ls https://localhost:5001

Error: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher
while server offers only version fallback.", DebugException="System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy
RequestVersionOrHigher while server offers only version fallback.
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")%
```

The issue is that Kestrel doesn't support HTTP/2 with TLS on macOS (https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-5.0#unable-to-start-aspnet-core-grpc-app-on-macos).

Maybe you could add a switch to disable TLS on the client-side, as described here?
https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-5.0#call-insecure-grpc-services-with-net-core-client

Thanks.

**Comment by bjorkstromm** [comment]
I used to have that workaround, but it shouldn't be needed anymore. https://github.com/bjorkstromm/dotnet-grpc-cli/commit/bedea1d61228afb797cc83fe95f96ccb068b6a1b

It should work automatically if you pass `http` instead of `https`.

E.g:
```
dotnet grpc-cli ls http://localhost:5000
```
(default http port is 5000, https is 5001)

You need to update to 0.5.0 of this tool to get it to work. https://www.nuget.org/packages/dotnet-grpc-cli/

**Comment by ChristianWeyer** [comment]
Yeah, this gives me...:

```
dotnet grpc-cli ls http://localhost:5000

Error: Status(StatusCode="Unavailable", Detail="Error starting gRPC call.
HttpRequestException: An error occurred while sending the request. IOException:
The request was aborted. Http2ConnectionException: The HTTP/2 server sent
invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1).",
DebugException="System.Net.Http.HttpRequestException: An error occurred while
sending the request.
 ---> System.IO.IOException: The request was aborted.
 ---> System.Net.Http.Http2ConnectionException: The HTTP/2 server sent invalid
data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1).
   at System.Net.Http.Http2Connection.ThrowProtocolError(Http2ProtocolErrorCode
errorCode)
   at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception
innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at
System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(Cancellatio
nToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request,
Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request,
Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage
request, Boolean async, Boolean doRequestAuth, CancellationToken
cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request,
Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request,
Nullable`1 timeout)")%
```

**Comment by bjorkstromm** [comment]
Unable to reproduce on both Windows and Linux when trying with a minimal repro. Unfortunately I don't have access to a Mac.

Are you able to reproduce with a minimal repro? E.g.
```
dotnet new grpc
dotnet add package Grpc.AspNetCore.Server.Reflection
```

and then adjust `Startup.cs` so it looks something like this:
```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddGrpc();
    services.AddGrpcReflection();
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }

    app.UseRouting();

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapGrpcService<GreeterService>();
        endpoints.MapGrpcReflectionService();

        endpoints.MapGet("/", async context =>
        {
            await context.Response.WriteAsync("Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");
        });
    });
}
```

**Comment by ChristianWeyer** [comment]
When starting with the code above, I immediately get the exception:

```
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to https://localhost:5001 on the IPv6 loopback interface: 'HTTP/2 over TLS is not supported on macOS due to missing ALPN support.'.
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
      System.IO.IOException: Failed to bind to address https://localhost:5001.
       ---> System.AggregateException: One or more errors occurred. (HTTP/2 over TLS is not supported on macOS due to missing ALPN support.) (HTTP/2 over TLS is not supported on macOS due to missing ALPN support.)
       ---> System.NotSupportedException: HTTP/2 over TLS is not supported on macOS due to missing ALPN support.
         at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.ValidateAndNormalizeHttpProtocols(HttpProtocols httpProtocols, ILogger`1 logger)
         at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware..ctor(ConnectionDelegate next, HttpsConnectionAdapterOptions options, ILoggerFactory loggerFactory)
         at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.<>c__DisplayClass12_0.<UseHttps>b__0(ConnectionDelegate next)
         at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.Build()
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass29_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
```

The code I used yesterday also adds gRPC-Web to the picture, which then successfully starts, but still does only do HTTP 1.1.

Using the code above, I need to use this:

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.ConfigureKestrel(options =>
                    {
                        // Setup a HTTP/2 endpoint without TLS.
                        options.ListenLocalhost(5000, o => o.Protocols =
                            HttpProtocols.Http2);
                    });

                    webBuilder.UseStartup<Startup>();
                });
```

Then your tools actually **works**.
This means, that it does not work with gRPC-Web enabled on the server, and the startup code above is not in place.

**Comment by ChristianWeyer** [comment]
I am not sure how to combine these two facts now :-) Having a TLS-less listener and having gRPC-Web enabled...

**Comment by bjorkstromm** [comment]
> This means, that it does not work with gRPC-Web enabled on the server, and the startup code above is not in place.

gRPC Server Reflection will not work on gRPC-Web, as gRPC Server Reflection required bi-directional streaming. The tool also doesn't use gRPC-Web. I'm not that familiar with gRPC-Web, but maybe it should be possible to have both gRPC and gRPC-Web enabled on a ASP.NET Core project.

**Comment by ChristianWeyer** [comment]
I am currently trying to convince Kestrel to have two ports, one with standard HTTPS and one with HTTP/2 without TLS....

**Comment by ChristianWeyer** [comment]
This is what works for me (at least in dev environment):
```

.ConfigureKestrel(options =>
{
    // all endpoints without TLS
    options.ListenLocalhost(5000, o => o.Protocols = HttpProtocols.Http2); // gRPC
    options.ListenLocalhost(5001, o => o.Protocols = HttpProtocols.Http1AndHttp2); // Web & gRPC-Web
})
```
