### ISSUE TITLE
Working with http/1.1

### ISSUE THREAD

**Issue by bballay-futeq** [bjorkstromm/dotnet-grpc-cli#4]
Hi! 

First of all -thanks for the amazing work done on this library :) I am having some trouble as my gRPC api is hosted in azure, hence I need to use gRPC-Web over http/1.1. When trying to use your tool, I am obviously getting following exception: 

Error: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while server    
offers only version fallback.", DebugException="System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while server offers 
only version fallback.
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")

Is it maybe possible to add supportfor gRPC-web ? 

Thank you so much :)

**Comment by bjorkstromm** [comment]
Hi @bballay-futeq, and thanks for the kind words. Unfortunately this tool can't support gRPC-Web as it's relying on gRPC server reflection. gRPC server reflection uses bi-directional streaming, which isn't supported by gRPC-Web.
